### ISSUE TITLE
Incompatible with Beanie 1.18

### ISSUE THREAD

**Issue by bkis** [fastapi-users/fastapi-users-db-beanie#11]
## Describe the bug

FastAPI-Users with fastapi-users-db-beanie seems to break when using the new Beanie release 1.18.  
The Beanie dependency for this project is set as `"beanie >=1.11.0,<2.0.0"`.

Any usage of (at least cookie-based) auth endpoints leads to:

```
  File "/home/user/.cache/pypoetry/virtualenvs/project-3OfolOSU-py3.10/lib/python3.10/site-packages/fastapi_users/authentication/strategy/db/strategy.py", line 46, in write_token
    return access_token.token
AttributeError: 'NoneType' object has no attribute 'token'
```

## To Reproduce

Just use it with Beanie `1.18`.

## Expected behavior

Everything works as intended.

## Configuration
- Python: `3.10`
- FastAPI: `0.95.1`
- FastAPI-Users: `10.4.0`
- FastAPI-Users-DB-Beanie: `1.1.4`
- Beanie: `1.18.0` <-- `1.17.x` worked just fine!

**Comment by frankie567** [comment]
Shall be fixed with [`fastapi-users-db-beanie==2.0.0`](https://github.com/fastapi-users/fastapi-users-db-beanie/releases/tag/v2.0.0).
